### ISSUE TITLE
Implement RPL_CREATIONTIME

### ISSUE THREAD

**Issue by yunginnanet** [lrstanley/girc#49]
First off, love girc. I have a ridiculous fork of it with a lot of wacky changes and have gotten pretty familiar with this masterpiece of yours.

Anyway, you're missing definition and handling of [code **329** AKA **RPL_CREATIONTIME**](https://modern.ircdocs.horse/#rplcreationtime-329). (details below)

<details>
<summary>Details</summary>

### RPL_CREATIONTIME (329)
`<client> <channel> <creationtime>`

> Sent to a client to inform them of the creation time of a channel. <channel> is the name of the channel. <creationtime> is a unix timestamp representing when the channel was created on the network.
</details>

----

I almost made a PR to add it for you into the definitions. However, after a bit of searching I'm not so sure it's in the RFC(s). Because of this I wasn't sure where exactly you'd want to place it, if at all.

 It is however, very prevalent and well-enough documented. It likely should be in constants, and if you're feeling cheeky enough, maybe even handled and stored in the channel state. (this is what I plan on doing with [girc-atomic](https://github.com/yunginnanet/girc-atomic)).

**Comment by lrstanley** [comment]
Sorry for the long delay on this, I believe I saw the issue awhile back but totally forgot about it. Should be added in https://github.com/lrstanley/girc/commit/b5af8a2128928b91b9cec3189d3016639800a6a7.

As far as non-RFC functionality when it comes to response codes, it's totally fine that those be added (in the misc section), since we don't map integer -> name, and only name -> integer, it allows overlapping easily, as I know a lot of IRC servers/clients don't follow the RFC.

I actually had planned to auto-generate all known response codes as constants via https://github.com/lrstanley/girc/issues/32 (utilizes ircdocs.horse and alien.net.au), however because it doesn't provide a huge amount of benefit, I've put that on hold for the time being.

**Comment by yunginnanet** [comment]
Thanks for the helpful response!
